# Generated by Django 2.2.28 on 2025-03-11 20:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BinThere', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='location',
            name='slug',
        ),
        migrations.AddField(
            model_name='bin',
            name='general',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='bin',
            name='glass',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='bin',
            name='metal',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='bin',
            name='organic',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='bin',
            name='overview',
            field=models.TextField(default='No overview provided'),
        ),
        migrations.AddField(
            model_name='bin',
            name='paper',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='bin',
            name='picture',
            field=models.ImageField(blank=True, null=True, upload_to='bin_pictures/'),
        ),
        migrations.AddField(
            model_name='bin',
            name='plastic',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='bintype',
            name='name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='location',
            name='latitude',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True),
        ),
        migrations.AlterField(
            model_name='location',
            name='longitude',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True),
        ),
        migrations.AlterField(
            model_name='location',
            name='name',
            field=models.CharField(max_length=100),
        ),
    ]
