# Generated by Django 2.2.28 on 2025-03-11 20:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BinThere', '0002_auto_20250311_2024'),
    ]

    operations = [
        migrations.AddField(
            model_name='location',
            name='slug',
            field=models.SlugField(blank=True, unique=True),
        ),
        migrations.AlterField(
            model_name='bintype',
            name='name',
            field=models.CharField(choices=[('PET Bottle', 'PET Bottle'), ('Glass', 'Glass'), ('Soft Plastic', 'Soft Plastic'), ('Paper', 'Paper'), ('Metal', 'Metal')], max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='location',
            name='latitude',
            field=models.DecimalField(decimal_places=6, default=0.0, max_digits=9),
        ),
        migrations.AlterField(
            model_name='location',
            name='longitude',
            field=models.DecimalField(decimal_places=6, default=0.0, max_digits=9),
        ),
        migrations.AlterField(
            model_name='location',
            name='name',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
