# Generated by Django 2.2.28 on 2025-03-11 21:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('BinThere', '0003_auto_20250311_2030'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='location',
            options={'verbose_name_plural': 'locations'},
        ),
    ]
