# Generated by Django 2.2.28 on 2025-03-11 21:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BinThere', '0004_auto_20250311_2105'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bin',
            name='bin_type',
        ),
        migrations.AddField(
            model_name='bin',
            name='bin_types',
            field=models.ManyToManyField(related_name='bins', to='BinThere.BinType'),
        ),
    ]
