# Generated by Django 2.2.28 on 2025-03-11 21:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BinThere', '0005_auto_20250311_2133'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bin',
            name='general',
        ),
        migrations.RemoveField(
            model_name='bin',
            name='glass',
        ),
        migrations.RemoveField(
            model_name='bin',
            name='metal',
        ),
        migrations.RemoveField(
            model_name='bin',
            name='organic',
        ),
        migrations.RemoveField(
            model_name='bin',
            name='paper',
        ),
        migrations.RemoveField(
            model_name='bin',
            name='plastic',
        ),
        migrations.AlterField(
            model_name='bintype',
            name='name',
            field=models.CharField(choices=[('PET Bottle', 'PET Bottle'), ('Glass', 'Glass'), ('Plastic', 'Plastic'), ('Paper', 'Paper'), ('Metal', 'Metal'), ('General', 'General'), ('Organic', 'Organic')], max_length=50, unique=True),
        ),
    ]
