# Generated by Django 2.2.28 on 2025-03-11 22:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('BinThere', '0006_auto_20250311_2145'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bintype',
            options={'verbose_name_plural': 'bin_types'},
        ),
    ]
