# Generated by Django 2.2.28 on 2025-03-12 19:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('BinThere', '0007_auto_20250311_2225'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bin',
            name='added_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='BinThere.UserProfile'),
        ),
    ]
