# Generated by Django 2.2.28 on 2025-03-12 19:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('BinThere', '0008_auto_20250312_1919'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bin',
            name='added_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
