# Generated by Django 2.2.28 on 2025-03-14 18:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BinThere', '0009_auto_20250312_1926'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vote',
            name='vote',
            field=models.SmallIntegerField(choices=[(1, 'Upvote'), (0, 'Downvote')]),
        ),
    ]
