# Generated by Django 2.2.28 on 2025-03-18 01:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BinThere', '0010_auto_20250314_1849'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='picture',
            field=models.ImageField(default='images/default_profile_picture.jpg', upload_to='profile_images'),
        ),
    ]
