# Generated by Django 2.2.28 on 2025-03-18 01:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BinThere', '0011_auto_20250318_0140'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='picture',
            field=models.ImageField(blank=True, upload_to='profile_images'),
        ),
    ]
