# Generated by Django 2.2.28 on 2025-03-21 20:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BinThere', '0012_auto_20250318_0151'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bintype',
            name='name',
            field=models.CharField(choices=[('Plastic Bottles', 'Plastic Bottles'), ('Mixed Glass', 'Mixed Glass'), ('Soft Plastic', 'Soft Plastic'), ('Paper', 'Paper'), ('Metal', 'Metal'), ('General', 'General'), ('Food Waste', 'Food Waste'), ('Textiles', 'Textiles'), ('Food and Drink Cans', 'Food and Drink Cans'), ('Cardboard', 'Cardboard'), ('Batteries', 'Batteries')], max_length=50, unique=True),
        ),
    ]
