# Generated by Django 2.2.28 on 2025-03-21 20:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BinThere', '0013_auto_20250321_2006'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bintype',
            name='name',
            field=models.CharField(choices=[('Plastic Bottles', 'Plastic Bottles')], max_length=50, unique=True),
        ),
    ]
